name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: read
  packages: write

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.5.x

      - name: Verify Deno installation
        run: deno --version

      - name: Cache Deno dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/deno
            ~/.deno
          key: ${{ runner.os }}-deno-${{ hashFiles('**/deno.json', '**/deno.lock') }}
          restore-keys: |
            ${{ runner.os }}-deno-

      - name: Install dependencies
        run: deno install --allow-scripts

      - name: Lint
        run: deno lint

      - name: Type check
        run: deno check main.ts

      - name: Run tests
        run: deno task test

      - name: Set version
        run: |
          VERSION="${{ github.ref_name }}"
          VERSION="${VERSION#v*}"
          echo "Version $VERSION"
          echo "VERSION=$VERSION" >> $GITHUB_ENV

  create-oci-image:
    name: Create OCI Image
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      # id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/NorskHelsenett/dcn-viti-network-policies-ssi
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          # platforms: linux/amd64,linux/arm64
          platforms: linux/amd64
          cache-from: type=gha
          cache-to: type=gha,mode=max

  publish-helm:
    if: github.ref_type == 'tag'
    runs-on: ubuntu-latest
    needs:
      - create-oci-image
    steps:
      - uses: actions/checkout@v4

      - name: Install helm
        uses: azure/setup-helm@v4
        with:
          version: v3.19.1

      - name: install-yq
        run: |
          wget https://github.com/mikefarah/yq/releases/download/${VERSION}/${BINARY}.tar.gz -O - | tar xz && mv ${BINARY} yq && chmod +x yq
        env:
          VERSION: v4.44.5
          BINARY: yq_linux_amd64

      - name: Build helm chart
        run: |
          export HELM_VERSION=${VERSION#v*}
          ./yq e -i '.version = strenv(HELM_VERSION),.appVersion = strenv(VERSION)' charts/dcn-viti-network-policies-ssi/Chart.yaml
          ./yq e -i '.image.tag = strenv(HELM_VERSION),.image.repository = "ncr.sky.nhn.no/ghcr/norskhelsenett/dcn-viti-network-policies-ssi"' charts/dcn-viti-network-policies-ssi/values.yaml
          helm package charts/dcn-viti-network-policies-ssi
          echo  ${{ secrets.GITHUB_TOKEN }} | helm registry login -u ${{ github.actor }} ghcr.io --password-stdin
          helm push dcn-viti-network-policies-ssi-${HELM_VERSION}.tgz oci://ghcr.io/norskhelsenett/helm/
        env:
          VERSION: ${{ github.ref_name }}
